### ISSUE TITLE
Publish GeoJSON-LD 1.0

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-ld#22]
## Minus temporal considerations!

Temporal context and vocab terms are forthcoming.
## Checklist
- [x] Remove temporal terms from the vocab pending approval
- [x] Copy vocab and context to geojson.github.io
- [x] Register and configure a purl.org domain for indentifiers (#43)
- [x] Change example.com URIs in vocab and context to purl.org URIs
- [x] Announce

**Comment by ekansa** [comment]
So I'm "bumping" this. Whatever that means. :)

**Comment by sgillies** [comment]
This is blocked by my lack of time to finish the Leaflet plugin (https://github.com/geojson/geojson-ld/issues/8). Question: power through that (I don't have time right now) or remove it from the checklist and continue? Running code is important, so I'm very hesitant to proceed without it.

@ekansa you've spoken to me before about putting a developer on a Leaflet plugin. Is that still possible?

**Comment by erictheise** [comment]
@sgillies, I'd be happy to work on the Leaflet plugin. Would make a lot of sense given the talk I've proposed for SotM US, though my concerns there are temporal.

**Comment by sgillies** [comment]
@erictheise Great! You want to try to pick up my pieces or start fresh?

**Comment by erictheise** [comment]
How about I decide after I look at the pieces, @sgillies?

**Comment by ekansa** [comment]
@erictheise please! That would be fantastic!

**Comment by akuckartz** [comment]
Ping!

Any news?

**Comment by sgillies** [comment]
@pietercolpaert what would you think about striking the Leaflet plugin off the list above and helping me with some examples? Maybe this thing can be shipped after all!

**Comment by ajturner** [comment]
:raised_hand: I would be interested in helping too. At first the how to would be useful then maybe clearer for others to write implementations.

Js.geo would be a good venue to have this ready to 'announce'

**Comment by pietercolpaert** [comment]
@sgillies I'm afraid I'm a bit over-committed at this moment and can't make any promises. If nothing has moved fwd in the next months, I'll take a look at it in October.

**Comment by sgillies** [comment]
@ajturner excellent. I've removed the Leaflet plugin from the list at the top of this issue.

**Comment by tstone** [comment]
Is this project still underway?  I am interested in using the `ld.geojson.org` vocabulary.

**Comment by sdrees** [comment]
Yes it is (@sgillies correct me if I am wrong) - but we are currently having GeoJSON RFC last call (exciting 👍 ), started work on GeoJSON Text Sequences, ... but we will continue to tackle the "linking" task. Maybe I can help more also with this, but at the moment do not want to risk over commitment ...

**Comment by sgillies** [comment]
In http://geojson.org/geojson-ld I have noted the outstanding issue with GeoJSON coordinates, which has not changed in over a year. I've seen that the JSON-LD working group is going to revive, but have not seen any signs that it will be interested in GeoJSON coordinates. I'm inclined to publish the vocabulary and context as they are, as "1.0", in the hopes that they will be more useful at some point in the future.

**Comment by azaroth42** [comment]
:+1: for moving forwards, and thank you for the hard work! 

Also thank you for the id/@id, type/@type mapping. It's great to see this pattern being adopted.

**Comment by akuckartz** [comment]
@sgillies We all are unhappy with the issue of JSON-LD regarding coordinates. I am pretty certain that a revived JSON-LD WG would seriously attempt to resolve it.

**Comment by sgillies** [comment]
Unless anyone finds a show stopper in the next week, I'll ship this on January 9.

**Comment by sgillies** [comment]
Received comments and a 👍 from Gregg Kellogg. I've pushed a new date-tagged version to http://geojson.org/geojson-ld/.

**Comment by ekansa** [comment]
Thanks Sean. I did some experiments using the new GeoJSON-LD contexts. Yes, the coordinates issue is super annoying. Hoping @akuckartz is right about getting solutions from the JSON-LD folks now that GeoJSON-LD adds some more motivating force.
