### ISSUE TITLE
How to express Geometry (polygon, myltiPoint ...) in geojson-ld

### ISSUE THREAD

**Issue by Roselin** [geojson/geojson-ld#26]
In the geojson, the polygon is expressed in the follow way.
 { "type": "Polygon",
    "coordinates": [
      [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]
      ]
   }
However, in JSON-ld, it is hard to transform to the RDF form with JSON-LD library.
Besides, JSON-ld not support array in array.
If we put the following format, then, it doesn't follow geojson.
 { "type": "Polygon",
    "coordinates": [
      "[ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]"
      ]
   }

**Comment by akuckartz** [comment]
?
