### ISSUE TITLE
Coordinate reference systems done right

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-ld#27]
Named and linked CRS, as specified in the original GeoJSON spec and current I-D, are disasters. GeoJSON-LD offers an easy way to get it right for datasets that absolutely have to have it. Something like this:

```
{ "@context": { 
    "geojson": "http://ld.geojson.org/vocab#", 
    "geojson:crs": {"@type": "@id"} },
  "geojson:crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
  "type": "FeatureCollection",
  ... }
```

Is the clearest solution I can think of.

**Comment by Chaz6** [comment]
I fully support a proper crs, as when exchanging geospatial data between systems it is essential that the crs is clearly defined.
