### ISSUE TITLE
Can we make an example showing GeoJSON-LD adding geo detail to existing JSON-LD data?

### ISSUE THREAD

**Issue by danbri** [geojson/geojson-ld#28]
I love the mission of "It offers a smooth path for upgrading existing GeoJSON data.", but what about flipping that around and also showing how this work could add richer geo detail to existing JSON-LD data?

(Said with a schema.org hat on, since we're encouraging JSON-LD usage, and http://schema.org/Place http://schema.org/GeoShape etc lack some detail. See https://github.com/rvguha/schemaorg/ for details).

**Comment by sgillies** [comment]
Closing. Future action at #31.
