### ISSUE TITLE
Develop and promote JSON-LD processor support for jsonld:jsonData

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-ld#31]
As suggested: https://github.com/geojson/geojson-ld/issues/28#issuecomment-64129489.

**Comment by fils** [comment]
Is this dead?  I'd love to see this example as I have some paleo scientists interested in this.

**Comment by ekansa** [comment]
And some archaeologists.

**Comment by sgillies** [comment]
@fils @ekansa Get on it, you two :)

**Comment by ekansa** [comment]
@sgillies human cloning has yet to be perfected.

@fils perhaps a small grant (NSF?) to hire a dev to build a Leaflet plugin?

**Comment by erictheise** [comment]
@fils, @ekansa, I told @sgillies I'd work on #8 between AAG and State of the Map, which is the next 3-4 weeks.

**Comment by ekansa** [comment]
@erictheise I'm working on an API for GeoJSON-LD with the when object: http://opencontext.dainst.org/about/services

Hope it is useful?

**Comment by sgillies** [comment]
I don't see the path forward on this one right now. Closing.
