### ISSUE TITLE
Develop a @ndarray container type

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-ld#34]
To complement @set and @list. See the note at the end of http://www.w3.org/TR/json-ld/#sets-and-lists about how lists of lists were left out of JSON-LD.

Our use for @ndarray in GeoJSON is to describe the `coordinates` member of geometry objects.

**Comment by akuckartz** [comment]
This is about a proposal for JSON-LD 2.0 ?

**Comment by akuckartz** [comment]
By convention the "@" indicates that the property belongs to JSON-LD. That was the reason for my last comment.

**Comment by dinizime** [comment]
And how exactly would be the RDF representation of a @ndarray?

I guess something like this could work:


But it is not useful at all...

**Comment by sgillies** [comment]
@dinizime I agree that RDF isn't useful. jsonld:JsonData (from https://github.com/geojson/geojson-ld/issues/28#issuecomment-64129489) works for me.

**Comment by dr-shorthair** [comment]
RDF is not designed/optimized for ordered lists/arrays. 
Not really for 'data' in the tables sense. 
Good for objects with heterogeneous properties, but not if the values of those properties include arrays.

**Comment by pietercolpaert** [comment]
I disagree with the comments stating that coordinates in RDF aren't useful. It's become a "holy discussion" within the geo-community whether geometry is 1 triple or multiple. We're not going to solve this today, but I would like to keep the option open for both solutions, as (in the future)[https://xkcd.com/644/], separate triples may find a particular use case.

In https://github.com/json-ld/json-ld.org/issues/397#issuecomment-153425387, we've discussed that it's going to be difficult to find a solution that just works for everything. I suggest we implement a converter, which is able to convert the GeoJSON-LD (a new mime type) proposed in #37, to JSON-LD.

**Comment by dinizime** [comment]
@pietercolpaert  Well, unfortunately, I need to be very practical. We literally don't have any tool that does spatial analysis in coordinates as a graph available today. On the other hand we have GeoSPARQL and stSPARQL available to deal with WKT.
But I agree with you that we must keep the option open...

**Comment by pietercolpaert** [comment]
An example of people actually converting geo shapes to RDF: http://nuts.geovocab.org/id/BE.html

**Comment by sgillies** [comment]
Sorry, folks. I don't see the way forward here. Closing.

**Comment by sgillies** [comment]
Hey, there are developments here: https://github.com/w3c/json-ld-syntax/pull/41. I think all interested persons should review and helpfully comment.
