### ISSUE TITLE
fix README.md

### ISSUE THREAD

**Issue by VladimirAlexiev** [geojson/geojson-ld#36]
Seems to me https://github.com/geojson/geojson-ld#example has a few errors. Have you tried converting it to eg turtle (eg using jena RIOT or the jsonld Playground)?

I also think it'd be appropriate to use `@vocab` (being the geojson vocab) so all terms without prefixes will automatically resolve to it.

Examples are very important since busy and/or not very cluefull people follow them blindly.

**Comment by sgillies** [comment]
Thanks for pointing this out.
