### ISSUE TITLE
CRS defintions missing

### ISSUE THREAD

**Issue by ThijsBroersen** [geojson/geojson-ld#45]
Hi,

Is the CRS part of the geojson specification not implemented on purpose?

**Comment by dret** [comment]
> On Apr 16, 2017, at 17:54, Thijs <notifications@github.com> wrote:
> Is the CRS part of the geojson specification not implemented on purpose?

on purpose: https://tools.ietf.org/html/rfc7946#appendix-B

**Comment by ThijsBroersen** [comment]
Did they lose their minds?! Many data-publishers do not publish in WGS84, reprojection is required and easily done. Linked Data can be used prefectly to publish CRS projection definitions and link to them inside GeoJSON just like the old specification had a linking definition.
