### ISSUE TITLE
Provide redirect from http://geojson.org/contexts/geojson-base.jsonld to http://geojson.org/geojson-ld/geojson-context.jsonld

### ISSUE THREAD

**Issue by mitar** [geojson/geojson-ld#46]
It seems that was renamed in the past. Now some old JSON-LDs I have cannot resolve.

**Comment by sgillies** [comment]
@mitar a redirect isn't possible but I came up with a fix.

**Comment by mitar** [comment]
Huh, great. I hope this will be kept in sync.

**Comment by sgillies** [comment]
No guarantees. Update your data if you can. That said, there are no plans to ever change geojson-context.jsonld and you shouldn't see any drift.
