### ISSUE TITLE
Current work?

### ISSUE THREAD

**Issue by KoalaGeo** [geojson/geojson-ld#50]
Hi, 

Is any work planned for GeoJSON-LD? 

https://www.w3.org/TR/json-ld11/ was recently published and wondered if that would impact GeoJSON-LD

Kind regards, 

Edd

**Comment by sgillies** [comment]
No. GeoJSON-LD is done.

**Comment by KoalaGeo** [comment]
Sorry so trying to get my head around the standards. 

Who's the custodian of GeoJSON-LD standard. Is it incorporated in RFC 7946 or part of W3C JSON 1.1? 

It's referenced in w3C docs...

**Comment by akuckartz** [comment]
@KoalaGeo See https://docs.ogc.org/is/17-003r2/17-003r2.html
